version: '2'
services:
  demo-app:
    image: demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-postgresql:5432/demo
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  demo-postgresql:
    extends:
      file: postgresql.yml
      service: demo-postgresql
