version: '2'
services:
  demo-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/demo/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
